// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Sample is an autogenerated mock type for the Sample type
type Sample struct {
	mock.Mock
}

// Greet provides a mock function with given fields:
func (_m *Sample) Greet() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Greet")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewSample creates a new instance of Sample. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSample(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sample {
	mock := &Sample{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
