// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Tested is an autogenerated mock type for the Tested type
type Tested struct {
	mock.Mock
}

// Greetings provides a mock function with given fields:
func (_m *Tested) Greetings() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Greetings")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewTested creates a new instance of Tested. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTested(t interface {
	mock.TestingT
	Cleanup(func())
}) *Tested {
	mock := &Tested{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
